schema_version: 1

context:
  name: econml
  version: 0.17.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/econml-${{ version }}.tar.gz
  sha256: b637b6166d290203775954c3af58c45a728a932315df3c334a625ab94e6e0b30

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scikit-learn >=1.6.0,<1.10
    - sparse >=0.15.4
    - joblib >=1.4.2
    - statsmodels >=0.14.4
    - pandas >=2.2.3
    - shap >=0.46.0
    - lightgbm >=4.5.0
    - packaging >=24.2
    - scipy >=1.13.1
    - numba >=0.60.0
  run_constraints:
    - dowhy <0.13

tests:
  - python:
      imports:
        - econml
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: This package contains several methods for calculating Conditional Average Treatment Effects
  license: MIT AND BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/py-why/EconML

extra:
  recipe-maintainers:
    - manuelwalserqc
    - norbertstoopqc
    - xhochy
    - pavelzw
